<a href="https://colab.research.google.com/github/ramboo1/RL/blob/main/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
R = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100]])

In [5]:
Q = np.matrix(np.zeros([6,6]))

In [6]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [7]:
gamma=0.8
initial_state=5

In [8]:
def available_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row>=0)[1]
  return av_act

In [9]:
available_act = available_actions(initial_state)

In [10]:
available_act

array([1, 4, 5])

In [11]:
def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_act,1))
  return next_action

In [12]:
action = sample_next_action(available_act)
action

5

In [13]:
def update(current_state,action,gamma):
  max_index = np.where(Q[action,]==np.max(Q[action,]))[1]

  if max_index.shape[0]>1:
      max_index = int(np.random.choice(max_index,size=1))
  else:
    max_index = int(max_index)
  max_value = Q[action, max_index]

  Q[current_state, action] = R[current_state, action] + gamma*max_value

  update(initial_state, action, gamma)

In [14]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [17]:
for i in range(10):
  current_state = np.random.randint(0, int(Q.shape[0]))
  available_act = available_actions(current_state)
  action = sample_next_action(available_act)
  update(current_state,action,gamma)


RecursionError: ignored

In [16]:
current_state=1
steps=[current_state]

while current_state != 5:
  next_step_index = np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index = int(np.random.choice(next_step_index,size=1))
  else:
    next_step_index = int(next_step_index)

  steps.append(next_step_index)
  current_state = next_step_index